site_name: Module 4
site_description: Creating and Deploying your first Serverless Function

nav:
  - Overview: index.md
  - Funqy Workflow: funqy-workflow.md
  - How It Works: how-it-works.md

plugins:
  - techdocs-core
